# Generated by Django 4.2.24 on 2025-09-13 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('status', models.CharField(max_length=50)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('deadline', models.DateField()),
                ('timespan', models.DurationField()),
            ],
        ),
    ]
